/**
 * Every page the daily SEO routine has written or rebuilt, newest last.
 *
 * app/sitemap.ts reads this: a path listed here gets `updated` as its
 * lastModified, and a path the static sitemap list does not have is added.
 * Add a row when a page ships. Change `updated` whenever its copy changes
 * materially, and in the same commit change PAGE.updated on the page itself.
 */
export type SeoPage = {
  path: string
  title: string
  /** One line: the question the page answers, the way a buyer asks it. */
  question: string
  kind: 'guide' | 'service' | 'industry' | 'case-study' | 'comparison'
  /** ISO dates, YYYY-MM-DD. */
  published: string
  updated: string
}

export const SEO_PAGES: SeoPage[] = [
  {
    path: '/how-we-make-an-ai-brand-film',
    title: 'How We Make an AI Brand Film: Brief to Final Cut',
    question: 'how are AI brand films made',
    kind: 'guide',
    published: '2026-09-14',
    updated: '2026-09-26',
  },
  {
    path: '/ai-video-production-agencies',
    title: 'AI Video Production Agency: How to Hire One',
    question: 'ai video production agency: what am I hiring and how do I pick one',
    kind: 'service',
    published: '2026-03-08',
    updated: '2026-10-03',
  },
  {
    path: '/ai-commercial-production',
    title: 'AI Commercial Production Company for Brands',
    question: 'ai commercial production company: which kind to hire, how an AI commercial is made, what it costs, and AI VFX on a live-action shoot vs a fully generated ad',
    kind: 'service',
    published: '2026-03-07',
    updated: '2026-10-06',
  },
  {
    path: '/blog/how-much-does-ai-video-production-cost',
    title: 'AI Video Production Cost: What Brands Pay',
    question: 'how much does ai video production cost, and how do AI video agencies price: per video, per campaign or per month',
    kind: 'guide',
    published: '2026-02-22',
    updated: '2026-09-29',
  },
  {
    path: '/comparison/ai-agency-vs-traditional-agency',
    title: 'AI Video Agency vs Traditional Production',
    question: 'ai video vs traditional video production: which should my brand hire, can AI replace a video production agency, and when should a brand hire an AI video production partner',
    kind: 'comparison',
    published: '2026-03-08',
    updated: '2026-10-05',
  },
  {
    path: '/ai-brand-film-agency',
    title: 'AI Brand Film Production for Companies',
    question: 'ai brand film: what is it, how is it made and what does it cost',
    kind: 'service',
    published: '2026-03-07',
    updated: '2026-09-26',
  },
  {
    path: '/ai-video-production-healthcare',
    title: 'AI Video for Pharma and Healthcare Marketing',
    question: 'can pharma, pharmacy, lab and medical companies use AI video, what will MLR ask, and what are the FDA rules for prescription drug TV and video ads',
    kind: 'industry',
    published: '2026-03-07',
    updated: '2026-10-03',
  },
  {
    path: '/guides/ai-video-character-consistency',
    title: 'AI Video Character Consistency for Brands',
    question: 'how do I keep the same character consistent across an AI video and the campaign photos',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/first-frame-last-frame-ai-video',
    title: 'First and Last Frame AI Video for Commercials',
    question: 'first frame last frame ai video: how does an AI commercial start from approved stills',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/brand-world-building',
    title: 'Brand World Building for AI Film and Photos',
    question: 'brand world building: how do I keep an AI brand film and its campaign photos in one world',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/brand-visual-dna',
    title: 'Brand Visual DNA: The Look Brief for AI Film',
    question: 'what is brand visual dna, and what does an AI film need on top of a photo brief',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/ai-commercial-product-accuracy',
    title: 'Product and Label Accuracy in AI Commercials',
    question: 'how do I keep my product, label and logo accurate in an AI commercial',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/commercial-production-budget-template',
    title: 'Commercial Production Budget Template for AI',
    question: 'commercial production budget template: what lines does an AI film and campaign stills budget need',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/ai-campaign-stack',
    title: 'AI Campaign Stack: Tools Behind Film and Stills',
    question: 'what tools make up an AI campaign stack, from stills to video to edit',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/ad-campaign-deliverables',
    title: 'Ad Campaign Deliverables: Film and Stills',
    question: 'ad campaign deliverables: which films, cutdowns and stills does each channel need',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/video-vs-static-ads',
    title: 'Video vs Static Ads: Where AI Film Fits',
    question: 'video vs static ads: which should I run, and where does an AI commercial fit',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/guides/ai-video-quality-control',
    title: 'AI Video Quality Control Before It Airs',
    question: 'ai video quality control: what do I check in an AI commercial before it airs',
    kind: 'guide',
    published: '2026-09-24',
    updated: '2026-09-24',
  },
  {
    path: '/markets/ai-video-production-canada',
    title: 'AI Video Production in Calgary and Canada',
    question: 'ai video agency calgary: which Calgary firms make AI video and how they differ, what it costs in Canada and which Canadian ad rules apply',
    kind: 'service',
    published: '2026-03-08',
    updated: '2026-10-06',
  },
  {
    path: '/ai-video-production-enterprise',
    title: 'AI Corporate Video Production for Companies',
    question: 'ai corporate video production: which company videos can be made with AI, enterprise platform or studio, are AI videos good enough for enterprise use, and what do they cost',
    kind: 'service',
    published: '2026-03-08',
    updated: '2026-10-05',
  },
  {
    path: '/guides/brands-using-ai-commercials',
    title: 'Brands Using AI Commercials: What Happened',
    question: 'what companies are using AI in their commercials, and how did audiences react',
    kind: 'guide',
    published: '2026-09-26',
    updated: '2026-09-26',
  },
  {
    path: '/best-video-production-company-calgary',
    title: 'Calgary Video Production Company: How to Choose',
    question: 'video production calgary: how do I choose a Calgary video production company, crew or AI studio',
    kind: 'guide',
    published: '2026-03-08',
    updated: '2026-09-27',
  },
  {
    path: '/affordable-video-production-calgary',
    title: 'Video Production Cost in Calgary: Real Prices',
    question: 'how much does video production cost in calgary',
    kind: 'guide',
    published: '2026-03-08',
    updated: '2026-09-27',
  },
  {
    path: '/blog/best-video-production-companies-calgary',
    title: 'Video Production Companies in Calgary: A List',
    question: 'video production companies calgary: who are they, what does each make, and which publish prices or offer AI video',
    kind: 'guide',
    published: '2026-03-08',
    updated: '2026-09-28',
  },
  {
    path: '/faq-ai-video-production',
    title: 'AI Video Production FAQ: Rights, Cost, Quality',
    question: 'can I use and copyright an AI video, is it legal, what does it cost and is it good enough',
    kind: 'guide',
    published: '2026-03-08',
    updated: '2026-09-30',
  },
  {
    path: '/ai-avatar-videos',
    title: 'AI Avatar Video Production for Companies',
    question: 'ai avatar video production company: when should a company use an AI avatar or spokesperson video, what does it cost, and tool or studio',
    kind: 'service',
    published: '2026-09-30',
    updated: '2026-09-30',
  },
  {
    path: '/guides/who-owns-ai-video',
    title: 'Who Owns an AI Video? Copyright for Brands',
    question: 'who owns the rights to an AI-generated commercial or brand film, and can it be copyrighted',
    kind: 'guide',
    published: '2026-09-30',
    updated: '2026-09-30',
  },
  {
    path: '/guides/ai-pharma-commercials',
    title: 'AI Pharma Commercials: Who Has Made Them',
    question: 'which pharma companies have made AI-generated commercials, is the saphnelo ad AI, and can drug ads use AI actors',
    kind: 'guide',
    published: '2026-10-01',
    updated: '2026-10-01',
  },
  {
    path: '/guides/ai-medical-animation',
    title: 'AI Medical Animation for Pharma and Labs',
    question: 'can ai make medical animation, what does a mechanism of action animation cost, and when should pharma hire a 3D medical animation studio instead',
    kind: 'guide',
    published: '2026-10-03',
    updated: '2026-10-03',
  },
  {
    path: '/ai-ugc-reels',
    title: 'AI UGC Ads Agency for Brands',
    question: 'ai ugc ads agency: what AI UGC ads cost, are they legal, and do you have to disclose an AI ad',
    kind: 'service',
    published: '2026-03-08',
    updated: '2026-10-04',
  },
  {
    path: '/ai-product-videos',
    title: 'AI Product Video Production for Brands',
    question: 'how much does a product video cost, and which AI can make product videos',
    kind: 'service',
    published: '2026-03-08',
    updated: '2026-10-04',
  },
]
